### PR TITLE
Add Retrode support (Thanks to revvv!)

### PR DESCRIPTION
**Pull request by bladeoner**

### CODE REVIEW

**Comment by bladeoner** [comment]
Compiled and tested, confirmed it works:
https://gbatemp.net/threads/snes9x-gx-forked-added-retrode-2-snes-gamepad-adapter.544686/

At first there was an issue compiling the Gamecube emulator which is fixed now.

**Comment by bladeoner** [comment]
revvv changed that it only starts polling the usb to look for the Retrode when it is connected, merged it in this PR.

**Comment by bladeoner** [comment]
I've added the change revvv made that when the device is not connected it won't be polling the USB port.

**Comment by dborth** [comment]
I've cleaned up this code and merged that instead. It's untested but it should work.

**Pull request closed without merging**
