### PR TITLE
Create Swedish translation

### PR DESCRIPTION
**Pull request by IsakTheHacker**

### CODE REVIEW

**Comment by dborth** [comment]
This won't work just on its own - some minor code changes need to be made to add Swedish as an option.

**Comment by IsakTheHacker** [comment]
Okay, I understand. Can you tell me what I need to add in the source code
and in which file? I think I will need to add "Swedish" as a translatable
string in all language files too, right?

**Comment by IsakTheHacker** [comment]
One more question, are the language files for your other emulator (fceugx) exactly the same? They seem very similar

**Comment by dborth** [comment]
I can make the changes to add Swedish.

Both vbagx and fceugx share the same project structure and so what a number of the other translators have done is create one translation file to be shared by all three, since additional translation strings that aren't used are harmless. A lot of the language used is the same in all 3 as possible so it's mostly only emulator-specific translations that differ.

**Comment by dborth** [comment]
Try the pre-release and see if everything works!

https://github.com/dborth/snes9xgx/releases

**Comment by dborth** [comment]
Thanks for the contributions! No there's no way to know that all strings are accounted for except by reviewing the source code and comparing to the translation file.

**Pull request merged**
