### PR TITLE
GameCube SD2SP2 fixes

### LINKED ISSUE #952: can't save game data on gcn using sd2sp2
on gcn, snes9xgx can load games from sd2sp2, but it can't load or save save data to it. also, there is no way to set sd2sp2 as the default device, you have to use sd gecko a or b and go to the top of the directory.

### PR DESCRIPTION
**Pull request by bladeoner**
This fixes loading and saving files using SD2SP2, tested it on a GameCube.

This might fix #952

### CODE REVIEW

**Comment by bladeoner** [comment]
@dborth, these changes are backported from a PR from emukidid:
https://github.com/niuus/Snes9xRX/pull/22

**Comment by dborth** [comment]
Yeah doesn't matter if it's called cardc or port2. that has no impact on this. there's only two things here:
- menu.cpp:3992 and 3394 - those indexes should've been updated - I missed that
- the auto-mounting was disabled on purpose at the time because detection was busted in libogc. I think that's fixed now.

**Comment by bladeoner** [comment]
Thanks for the explanation, shall I close the PR?

**Comment by dborth** [comment]
As always, appreciate the effort and keeping up with what's going on with other projects.

**Pull request closed without merging**
