### PR TITLE
Add automated build via Cirrus CI

### PR DESCRIPTION
**Pull request by bladeoner**
@dborth This change enables automated build via Cirrus CI.

The build is succesful which gives us a good overview if code that will be merged into the source will break anything.

At this point the compiled files are giving me a black screen when booting so the emulators that are compiled are not yet functional, but for now we can use it to see how compiling goes when merging code. 
I cannot update the Cirrus CI devkitPro environment to see if that fixes it because that will break the compile process.

Updating to the latest devkitPro tools also broke the compile on my machine I opened an issue here. 
Don't know if you have an idea what is going on, I have added my logfile.

To get the Cirrus CI to work it requires you do perform some steps:
- Go to the following website, click "Public Repositories" en click on "Install it for free" on the right side: https://github.com/marketplace/cirrus-ci
- Then click on "Complete order and begin installation" (it's completely free).
- Then you can select "All repositories" or "Only select repositories".
I would suggest "Only select repositories" and select 'snes9xgx', 'fceugx' and 'vbagx'. 
I don't know if you have more repositories you want to implement this for.
- After that click on 'Install' and that should be all.
- When you go to Github click on your Profile, click on settings, click on Applications, you will see Cirrus CI and you can click Configure and Add or adjust the settings like before.

The builds are continuously after a commit or after you add some code to a branch.

I've added the Freetype (older version we use) to the source because it will be downloaded on the Cirrus CI server and copied over the one that is already installed on that machine. 

It works with profiles so it's a docker machine at Cirrus CI with Linux and devkitPro tools pre-installed.

### CODE REVIEW

**Comment by carstene1ns** [comment]
Question: Why is the old freetype needed? API is compatible, so should be possible to use the latest.
Btw. GitHub Actions could also be used as they offer docker-based compilation actions as well, so no external service is needed.

Good idea to add CI/CD! :)

**Comment by dborth** [comment]
For some reason linking in the devkitpro compile of freetype causes a crash in wiiuse in the emulator. I only discovered the cause was freetype through trial and error. I have yet to test if this is fixed on the newest devkitppc and we can switch back. I also never did try compiling freetype myself to see if that made a difference.

**Comment by dborth** [comment]
Yup, just checked again. Same thing. There's something wrong with the ppc-freetype build from devkitpro.

**Comment by bladeoner** [comment]
@carstene1ns the Cirrus CI has a devkitPro docker machine don't know if github has one. For now the build also doesn't work but it gives us more information.

**Comment by carstene1ns** [comment]
@bladeoner Well, you can use every image available on dockerhub, which is the same with cirrus-ci I guess.
As said it does not really matter which CI/CD solution is used.

@dborth That crash is really interesting, might be worth to build freetype without bz2 and png support for testing.

**Pull request merged**
