### PR TITLE
Backport Reduced version of Vitor's fix for SA1 speed throttle

### PR DESCRIPTION
**Pull request by bladeoner**
Backported: Reduced version of Vitor's fix for SA1 speed throttle.

Removed: SA1 hack.

Tested following SA1 games:
Jikkyou Oshaberi Parodius, much better FPS
Kirby Superstar, no issues with the intro
Super Mario RPG
Kirby's Dreamland 3

### CODE REVIEW

**Comment by askotx** [comment]
Could you test also Kirby's Dream Land 3 and Dragon Ball Z: Hyper Dimension? They also use SA1 chip. In Kirby wait for intro until appear Kirby with Rick (Hamster) jumping over some rocks, performance has been dropped from 54~58/60 FPS (4.3.7) to 48~54/FPS (4.3.9~4.4.1)

**Comment by bladeoner** [comment]
@askotx I have tested Kirby it's around 54-58/60 FPS with Rick (Hamster), I don't have Dragon Ball Z: Hyper Dimensions. But I can share the compiled file which is
[Snes9x.GX.4.4.1_SA1_Test.zip](https://github.com/dborth/snes9xgx/files/2751109/Snes9x.GX.4.4.1_SA1_Test.zip)

**Comment by bladeoner** [comment]
Tested Super Mario RPG, without this change it's 59/60, with this change it drops to 55/60.

**Comment by bladeoner** [comment]
Tested it some more works really good actually.

**Pull request merged**
