### PR TITLE
Allow "Original" (240p) render mode in 480p configurations (Taken from niuus' Snes9x RX)

### PR DESCRIPTION
**Pull request by saulfabregwiivc**
This commit/contribution was taken originally from Snes9x RX, a fork of Snes9x GX by @niuus. More info: https://github.com/niuus/Snes9xRX/commit/4f4627fe

This will allow "Original" render mode to be selectable when using the Wii Options TV Resolution setting for "EDTV or HDTV (480p)" over component cables:
- This caters specifically to LCD / LED users with 240p supported displays, since the option was previously hidden. Users with CRT / PVM / BVM displays with supported 480p Progressive Scan mode will also benefit, since no Wii setting switch will be needed for the "Original" 240p mode to be used.
Hope this will be added to Snes9x GX soon.

@saulfabregwiivc

### CODE REVIEW

**Comment by saulfabregwiivc** [comment]
Today tested the build with that commit i'm trying to add to main Snes9x GX.
It worked like a charm. Tested in Dolphin emulator and works.

Obviously your TV must support 240p resolution for use "Original" when your Wii settings of TV Resolution is in "EDTV or HDTV (480p)".

**Comment by dborth** [comment]
This is fine, but why are we flipping sharp and soft around?

**Comment by saulfabregwiivc** [comment]
> This is fine, but why are we flipping sharp and soft around?

The original commit fron @niuus flipped that, but i've tested it and it didn't notice any confusion between that two even when flipped.
Well, if you don't want those settings flipped, i will fix them for you in a new commit for this pull request.

**Comment by saulfabregwiivc** [comment]
Order of Filtered Sharp/Soft settings fixed.

**Pull request merged**
